### ISSUE TITLE
[Bug] Darkness zombie and Shadow MTF cant blackout surface with their ability

### ISSUE THREAD

**Issue by Sansrequiem5** [ChaosTheoryScp/IssueTracker#114]
**Description:**
when attempting to press alt and activate their ability to blackout the room they are in, nothing will happen and their ability will be put on cooldown

**To Reproduce:**
spawn / be revived as a shadow MTF / darkness zombie
press alt to try and use your ability
**Expected behavior:**
the surface zone should blackout like usual

**Video:**
https://medal.tv/games/scp-secret-laboratory/clips/jnveWKN30Oj_F69fq?invite=cr-MSw3VEIsMjAwMjY2ODYwLA

**Discord Link:**
https://discord.com/channels/956245649534378124/1322715042604646424

**Comment by TtroubleTT** [comment]
Seems to be fixed in new exiled
