### ISSUE TITLE
[Bug] Jugg cannot fit through the surface nukeroom door

### ISSUE THREAD

**Issue by Sansrequiem5** [ChaosTheoryScp/IssueTracker#126]
**Description:**
when a CI jugg spawns in, they will be unable to enter the surface nukeroom due to their bigger size

**To Reproduce:**
1. spawn as CI jugg
2. attempt to enter surface nukeroom
**Expected behavior:**
the size increase should not be enough to prevent the entry, and they are able to enter nuke just fine

**Video:**
https://medal.tv/games/scp-secret-laboratory/clips/jo0IbNqurrX2p8keY?invite=cr-MSxBZFQsOTU3ODY1NDEs

**Discord Link:**
Confirmed Bug link: https://discord.com/channels/956245649534378124/1322266569929396336
Bug report link: https://discord.com/channels/956245649534378124/1322106898195157044

**Comment by TtroubleTT** [comment]
Fixed
