### ISSUE TITLE
[Bug] Kevlar unit's dmg reduction tip is displayed as 35% despite only being 30% in game

### ISSUE THREAD

**Issue by Sansrequiem5** [ChaosTheoryScp/IssueTracker#151]
**Description:**
when looking at info of kevlar unit, it still says its 35%, despite being changed to 30 in the patchnotes

**To Reproduce:**
become kevlar unit
type .info in console to view info

**Expected behavior:**
it should say its only  30%

**Video:**
not clipped, still image in the discord report

**Discord Link:**
https://discord.com/channels/956245649534378124/1322151917111087136

**Comment by TtroubleTT** [comment]
Fixed
